name: Container Scan (Trivy)

on:
  push:
    branches: [ main ]
    paths:
      - '**/Dockerfile'
  workflow_dispatch:

jobs:
  trivy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@v0.12.0
        with:
          scan-type: fs
          ignore-unfixed: true
          severity: CRITICAL,HIGH
